name: Lecture environment file
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pillow
  - scikit-learn
  - keras
  - tensorflow
  - nbgitpuller
  - ipywidgets
  - jupyter_contrib_nbextensions
  - cartopy
